spring:
  application:
    name: challenge
  datasource:
    url: ${DB_HOST}
    driver-class-name: org.postgresql.Driver
    username: posfiap
    password: posfiap2

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always